### ISSUE TITLE
设置了__SCRIPTS.ubbeditor好像没起作用

### ISSUE THREAD

**Issue by mlzzen** [zeg/nga_ubb_editor_v2#1]
还是没请求我本地服务的index.html呢

@iomect 老哥求助

**Comment by iomect** [comment]
在可视化编辑器加载前就需要在控制台输入命令
之后再点击切换可视化编辑器
不要在-7测试  在-7版面默认会打开内嵌的旧版编辑器

**Comment by mlzzen** [comment]
感谢，没问题了，昨天晚上我测试到折叠功能有点问题，现在好像已经修复了。
